name: Deploy DNS Setup


# on:
#   workflow_call:
#     inputs:
#       AWS_DEFAULT_REGION:
#         required: true
#         type: string
#         default: us-east-1


on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read  # Required for downloading artifacts

jobs:
  setup_dns:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout main repo
      #  uses: actions/checkout@v3

      - name: Checkout Terraform Repo
        uses: actions/checkout@v2
        with:
          repository: deshpandeshantanu96/terraform-repo
          token: ${{ secrets.TERRAFORM_REPO_TOKEN }}
          path: terra  # Check out into "terra" folder

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./terra

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        working-directory: ./terra
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Debug - List files in terra
        run: ls -R
        working-directory: ./terra

      - name: Verify AWS Credentials
        working-directory: ./terra
        run: |
          aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

      - name: Run DNS Setup Script
        working-directory: ./terra
        run: |
          python create_dns_record.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
