name: Deploy DNS Setup

on:
  workflow_call:
    inputs:
      AWS_DEFAULT_REGION:
        required: true
        type: string
        default: us-east-1

permissions:
  contents: read
  actions: read

jobs:
  setup_dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout Terraform Repo
        uses: actions/checkout@v2
        with:
          repository: deshpandeshantanu96/terraform-repo
          token: ${{ secrets.TERRAFORM_REPO_TOKEN }}
          path: terra

      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./terra

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        working-directory: ./terra
        run: |
          python -m pip install --upgrade pip
          pip install boto3
      
      - name: Verify Repository Contents
        working-directory: ./terra
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Searching for Python script..."
          find . -name "*.py" -type f

      - name: Run DNS Setup Script
        working-directory: ./terra
        run: |
          # First try root directory
          if [ -f "create_dns_record.py" ]; then
            python create_dns_record.py
          # Then check common locations
          elif [ -f "scripts/create_dns_record.py" ]; then
            python scripts/create_dns_record.py
          elif [ -f "dns/create_dns_record.py" ]; then
            python dns/create_dns_record.py
          else
            echo "ERROR: create_dns_record.py not found!"
            find . -type f -name "*.py"
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}