# name: Deploy DNS Setup

# on:
#   push:
#     branches: [ main ]  # or your preferred branch
#   workflow_call:
#     inputs:
#       AWS_DEFAULT_REGION:
#         required: true
#         type: string
#         default: us-east-1

name: Deploy DNS Setup

on:
  push:
    branches: [main]

jobs:
  setup_dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        
      - name: Checkout terraform-repo
        uses: actions/checkout@v3
        with:
          repository: deshpandeshantanu96/terraform-repo
          token: ${{ secrets.TERRAFORM_REPO_TOKEN }}
          path: terraform-repo

      - name: Run DNS script
        run: python terraform-repo/create_dns_record.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'