name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read  # Added for artifact sharing

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Checkout Terraform Repo
        uses: actions/checkout@v2
        with:
          repository: deshpandeshantanu96/terraform-repo  # Replace with your terraform-repo
          token: ${{ secrets.TERRAFORM_REPO_TOKEN }}  # Your GitHub token
          path: terraform  # Path where the Terraform code will be checked out

      - name: Checkout Terraform Repo
        uses: actions/checkout@v2
        with:
          repository: deshpandeshantanu96/tfvars-repo  # Replace with your terraform-repo
          token: ${{ secrets.TFVAR_REPO_TOKEN }}  # Your GitHub token
          path: tfvar  # Path where the Terraform code will be checked out

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false -var-file="../tfvar/terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false -var-file="../tfvar/terraform.tfvars"

      - name: Export Terraform Outputs
        working-directory: ./terraform
        run: 
          terraform output -json > terraform_outputs.json
      
      - name: Clean Terraform Outputs
        run: |
          grep -v '^::debug::' terraform_outputs.json | jq . > temp.json && \
          mv temp.json terraform_outputs.json
          echo "Cleaned JSON output:"
          head -n 5 terraform_outputs.json
          
      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: terraform_outputs.json

  dns_setup:
    needs: terraform
    uses: ./.github/workflows/deploy_dns.yml
    with:
      AWS_DEFAULT_REGION: us-east-1
    secrets: inherit

#Step: 133